# Generated by Django 4.2.7 on 2023-12-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='number',
            field=models.CharField(max_length=255),
        ),
    ]
